spring:
    datasource:
        url: 'jdbc:postgresql://localhost:5432/rupt-bank'
        username: 'postgres'
        password: ${POSTGRES_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
